### ISSUE TITLE
[REQ功能请求] 首页-附近 的照片墙，可基于ID隐藏头像

### ISSUE THREAD

**Issue by luboq** [EricMo/BluedHook#2]
作为非代码贡献者，胆战心惊提个REQ：

首页-附近 的照片墙，能不能长按某人头像后，选择“隐藏”（或点进Ta主页后，选择隐藏）？以后在附近的照片墙中，就看不到Ta了。操作基于ID，隐藏效果 在换头像后依然有效

因为有些附近的人，聊过后不感兴趣，就没必要占据屏幕了。首页留下那些，愿意关注的“附近”朋友，和新的朋友。让附近的人 这个页面，更有“效能”一点（如果效能这个词不好听，就更好用一点吧）

内置的黑名单，虽然可以做这点，但第一，黑名单人数上限太低，第二，黑名单带有敌意，一旦拉黑后，双方无法私聊；隐藏则是中性的，只代表”在附近的人这个页面“不关心Ta，但假如真有需要，Ta仍然能联系到我，我也能联系到Ta（从关注/被关注/来访/查看 都能找到Ta）
——所以我觉得，黑名单不能替代隐藏。单独的“隐藏“，挺有用的

当然，免费开源作品，**只表达下个人愿望，不实现也没关系**。谢谢带来这个作品

**Comment by EricMo** [comment]
@waldens 可以考虑一下
