### ISSUE TITLE
可否增加blued international 2.2.0版本

### ISSUE THREAD

**Issue by eno1a** [EricMo/BluedHook#3]
大神你好。国际版2.2.0版本可以直接看到私密相册。。能否在这个版本的基础上出个hook。。谢谢、、

**Comment by eno1a** [comment]
我试着把你的代码fork下来自己改，但是水平有限 55555555

**Comment by EricMo** [comment]
@eno1a 国际版我在国内是等不不上去的。所以，我是没办法去适配的。
