### ISSUE TITLE
blued升级后息屏在打开就失效了

### ISSUE THREAD

**Issue by ly0817** [EricMo/BluedHook#4]
后面退回旧的blued也是，刚安装好没问题，但是只要退出，息屏再打开插件就失效了，只有卸载blued后重新安装才能生效，但是息屏后又失效

**Comment by EricMo** [comment]
闪照是否可用？最新版的Blued修改了用户信息相关代码，造成vip功能失效。

**Comment by ly0817** [comment]
息屏重开软件后所有功能都不可用了，所以我后面重新下了旧的APP，但是还是会出现同样的问题，后面我重新用了旧版本的插件也还是有这样的问题，不太清楚造成的原因是什么，总之现象就是新版本的APP插件不可用，回退到旧版本APP和插件后，安装APP后插件有效果，但是息屏或者重新开APP后，插件就失效了，重启手机或者框架也没有用，只有卸载APP后重新装插件才会生效，但是同样息屏或者重新开APP后插件就失效了

**Comment by EricMo** [comment]
@ly0817 机型，ROM,运行环境，blued版本，插件版本提供一下。

**Comment by ly0817** [comment]
努比亚X，刷的miui10.2.33 ,edxposed90.0-0.3.17-beta框架，blued_6.7.6，插件1.13，没有升级最新app之前插件运行一切正常，就是升级之后发现插件失效，然后回退app，接着就出现息屏或者重新开APP后插件失效的问题
